import csv

# Elenco di 200 aziende italiane (o grandi gruppi operanti in Italia)
# che hanno redatto il bilancio di sostenibilità/DNF nel 2023-2024.
# Dati categorizzati per Macro-Settore e Codice ATECO principale.

aziende = [
    # --- MANIFATTURA E MECCANICA (ATECO 25-28) ---
    ["Brembo S.p.A.", "Manifattura / Automotive", "29.32"],
    ["Pirelli & C. S.p.A.", "Manifattura / Automotive", "22.11"],
    ["Leonardo S.p.A.", "Manifattura / Aerospazio", "30.30"],
    ["Fincantieri S.p.A.", "Manifattura / Cantieristica", "30.11"],
    ["Interpump Group S.p.A.", "Manifattura / Meccanica", "28.13"],
    ["Danieli & C. Officine Meccaniche S.p.A.", "Manifattura / Meccanica", "28.91"],
    ["Biesse S.p.A.", "Manifattura / Macchinari", "28.49"],
    ["Prima Industrie S.p.A.", "Manifattura / Macchinari", "28.41"],
    ["Piaggio & C. S.p.A.", "Manifattura / Automotive", "30.91"],
    ["De' Longhi S.p.A.", "Manifattura / Automotive", "30.91"],
    ["Carraro S.p.A.", "Manifattura / Meccanica", "28.15"],
    ["Datalogic S.p.A.", "Manifattura / Elettronica", "26.20"],
    ["Luve S.p.A.", "Manifattura / Meccanica", "28.25"],
    ["SABAF S.p.A.", "Manifattura / Meccanica", "28.14"],
    ["Carel Industries S.p.A.", "Manifattura / Elettronica", "26.51"],
    ["Ariston Holding N.V.", "Manifattura / Elettrodomestici", "27.51"],
    ["Elica S.p.A.", "Manifattura / Elettrodomestici", "27.51"],
    ["Indel B S.p.A.", "Manifattura / Elettrodomestici", "27.51"],
    ["GVS S.p.A.", "Manifattura / Componenti", "22.29"],
    ["Aquafil S.p.A.", "Manifattura / Meccanica", "28.25"],
    ["BFT S.p.A.", "Manifattura / Componenti", "28.14"],
    ["Cembre S.p.A.", "Manifattura / Componenti", "28.14"],
    ["Gefran S.p.A.", "Manifattura / Elettronica", "26.51"],
    ["Eurotech S.p.A.", "Manifattura / Elettronica", "26.51"],
    ["Landi Renzo S.p.A.", "Manifattura / Automotive", "29.32"],
    ["Lafert Group", "Manifattura / Motori Elettrici", "27.11"],
    ["Coesia S.p.A.", "Manifattura / Macchinari", "28.99"],
    ["Forgital Group", "Manifattura / Forgiatura", "25.50"],
    ["Fonderie Ariotti", "Manifattura / Fonderia", "24.51"],
    ["RX PACK", "Manifattura / Plastica", "22.22"],
    ["Oerlikon Friction Systems", "Manifattura / Componenti", "29.32"],
    ["Raccortubi S.p.A.", "Manifattura / Componenti", "25.99"],
    ["Zoppas Industries", "Manifattura / Elettrodomestici", "27.51"],
    ["Bonfiglioli Riduttori", "Manifattura / Meccanica", "28.15"],
    ["Marchesini Group", "Manifattura / Macchinari", "28.49"],
    ["SCM Group", "Manifattura / Macchinari", "28.49"],
    ["Sacmi", "Manifattura / Macchinari", "28.99"],
    ["GIMA TT", "Manifattura / Macchinari", "28.99"],
    ["IMA S.p.A.", "Manifattura / Macchinari", "28.99"],
    ["Same Deutz-Fahr (SDF)", "Manifattura / Macchine Agricole", "28.30"],

    # --- AGROALIMENTARE E BEVERAGE (ATECO 10-11) ---
    ["Barilla G. e R. Fratelli S.p.A.", "Alimentare", "10.71"],
    ["Ferrero S.p.A.", "Alimentare", "10.82"],
    ["Lavazza S.p.A.", "Alimentare", "10.83"],
    ["Illycaffè S.p.A.", "Alimentare", "10.83"],
    ["Campari Group", "Beverage", "11.01"],
    ["Granarolo S.p.A.", "Alimentare / Lattiero", "10.51"],
    ["Parmalat S.p.A.", "Alimentare / Lattiero", "10.51"],
    ["Amadori S.p.A.", "Alimentare / Carni", "10.12"],
    ["AIA - Agricola Italiana Alimentare", "Alimentare / Carni", "10.12"],
    ["De Cecco S.p.A.", "Alimentare / Pasta", "10.71"],
    ["La Doria S.p.A.", "Alimentare / Conserve", "10.39"],
    ["Mutti S.p.A.", "Alimentare / Conserve", "10.39"],
    ["Conserve Italia", "Alimentare / Conserve", "10.39"],
    ["Sanpellegrino S.p.A.", "Beverage", "11.07"],
    ["Ferrarelle S.p.A.", "Beverage", "11.07"],
    ["Acqua Sant'Anna S.p.A.", "Beverage", "11.07"],
    ["Lete S.p.A.", "Beverage", "11.07"],
    ["Bauli S.p.A.", "Alimentare / Dolciario", "10.52"],
    ["Sammontana S.p.A.", "Alimentare / Dolciario", "10.52"],
    ["Galbusera S.p.A.", "Alimentare / Dolciario", "10.71"],
    ["Balocco S.p.A.", "Alimentare / Dolciario", "10.71"],
    ["Rovagnati S.p.A.", "Alimentare / Carni", "10.13"],
    ["Citterio S.p.A.", "Alimentare / Carni", "10.13"],
    ["F.lli Saclà S.p.A.", "Alimentare / Conserve", "10.39"],
    ["Ponti S.p.A.", "Alimentare / Conserve", "10.39"],
    ["Rigoni di Asiago", "Alimentare / Conserve", "10.39"],
    ["Novi S.p.A.", "Alimentare / Dolciario", "10.82"],
    ["Zonin1821", "Beverage / Vino", "11.02"],
    ["Marchesi Antinori", "Beverage / Vino", "11.02"],
    ["Masi Agricola", "Beverage / Vino", "11.02"],
    ["La Granda Trasformazione S.r.l.", "Alimentare / Carni", "10.11"],
    ["Vis Industrie Alimentari", "Alimentare / Pesce", "10.20"],
    ["Montanari & Gruzza", "Alimentare / Lattiero", "10.51"],
    ["Simone Gatto S.r.l.", "Alimentare / Agrumi", "10.32"],
    ["CAAT Centro Agroalimentare Torino", "Alimentare / Logistica", "46.31"],
    ["Salumificio Fratelli Beretta", "Alimentare / Carni", "10.13"],
    ["Colussi S.p.A.", "Alimentare / Dolciario", "10.72"],
    ["Vicenzi S.p.A.", "Alimentare / Dolciario", "10.72"],
    ["Fabbri 1905", "Alimentare / Dolciario", "10.82"],
    ["Eridania", "Alimentare / Zucchero", "10.81"],

    # --- ENERGIA, UTILITY E AMBIENTE (ATECO 35-39) ---
    ["Enel S.p.A.", "Energia / Utility", "35.11"],
    ["Eni S.p.A.", "Energia / Oil & Gas", "19.20"],
    ["Terna S.p.A.", "Energia / Trasmissione", "35.12"],
    ["Snam S.p.A.", "Energia / Trasmissione", "35.22"],
    ["A2A S.p.A.", "Energia / Utility", "35.11"],
    ["Hera S.p.A.", "Energia / Utility", "35.11"],
    ["Iren S.p.A.", "Energia / Utility", "35.11"],
    ["Acea S.p.A.", "Energia / Utility", "35.11"],
    ["Erg S.p.A.", "Energia / Utility", "35.11"],
    ["Saras S.p.A.", "Energia / Oil & Gas", "19.20"],
    ["Ascopiave S.p.A.", "Energia / Utility", "35.22"],
    ["Italgas S.p.A.", "Energia / Trasmissione", "35.22"],
    ["Edison S.p.A.", "Energia / Utility", "35.11"],
    ["Falck Renewables (Renantis)", "Energia / Rinnovabili", "35.11"],
    ["Alerion Clean Power S.p.A.", "Energia / Rinnovabili", "35.11"],
    ["Gruppo CAP", "Utility / Acqua e Rifiuti", "36.00"],
    ["Acquedotto Pugliese", "Utility / Acqua", "36.00"],
    ["SMAT S.p.A.", "Utility / Acqua", "36.00"],
    ["Marche Multiservizi", "Utility / Ambiente", "38.11"],
    ["Contarina S.p.A.", "Utility / Ambiente", "38.11"],

    # --- MODA, TESSILE E LUSSO (ATECO 13-15) ---
    ["Moncler S.p.A.", "Moda / Lusso", "14.13"],
    ["Brunello Cucinelli S.p.A.", "Moda / Lusso", "14.13"],
    ["Salvatore Ferragamo S.p.A.", "Moda / Lusso", "14.13"],
    ["Tod's S.p.A.", "Moda / Lusso", "15.20"],
    ["Prada S.p.A.", "Moda / Lusso", "15.20"],
    ["Gucci (Kering Italia)", "Moda / Lusso", "15.20"],
    ["Armani (Kering Italia)", "Moda / Lusso", "14.13"],
    ["Valentino S.p.A.", "Moda / Lusso", "14.13"],
    ["OTB Group (Diesel, Marni)", "Moda", "14.13"],
    ["OVS S.p.A.", "Moda / Retail", "47.71"],
    ["BasicNet S.p.A.", "Moda / Abbigliamento Sportivo", "14.19"],
    ["Geox S.p.A.", "Moda / Calzature", "15.20"],
    ["Aeffe S.p.A.", "Moda / Abbigliamento Sportivo", "14.19"],
    ["Piquadro S.p.A.", "Moda / Pelletteria", "15.12"],
    ["Marzotto Group", "Tessile", "13.20"],
    ["Zegna Group", "Moda / Lusso", "14.13"],
    ["Clerici Tessuto", "Tessile", "13.20"],
    ["Ratti S.p.A.", "Tessile", "13.20"],
    ["RadiciGroup", "Tessile / Chimica", "13.10"],
    ["Alcantara S.p.A.", "Tessile", "13.20"],

    # --- SERVIZI FINANZIARI E ASSICURATIVI (ATECO 64-66) ---
    ["Intesa Sanpaolo S.p.A.", "Finanza / Banche", "64.19"],
    ["UniCredit S.p.A.", "Finanza / Banche", "64.19"],
    ["Banco BPM S.p.A.", "Finanza / Banche", "64.19"],
    ["BPER Banca S.p.A.", "Finanza / Banche", "64.19"],
    ["Banca Mediolanum S.p.A.", "Finanza / Banche", "64.19"],
    ["Banca Popolare di Sondrio", "Finanza / Banche", "64.19"],
    ["Credito Emiliano (BPER)", "Finanza / Banche", "64.19"],
    ["Mediobanca S.p.A.", "Finanza / Banche", "64.19"],
    ["FinecoBank S.p.A.", "Finanza / Banche", "64.19"],
    ["Generali S.p.A.", "Finanza / Assicurazioni", "65.12"],
    ["UnipolSai Assicurazioni", "Finanza / Assicurazioni", "65.12"],
    ["Cattolica Assicurazioni", "Finanza / Assicurazioni", "65.12"],
    ["Poste Italiane S.p.A.", "Finanza / Servizi Postali", "64.19"],
    ["Azimut Holding S.p.A.", "Finanza / Gestione Risparmio", "64.99"],
    ["Anima Holding S.p.A.", "Finanza / Gestione Risparmio", "64.99"],
    ["Nexi S.p.A.", "Finanza / Banche", "64.19"],
    ["Banca Ifis S.p.A.", "Finanza / Banche", "64.19"],
    ["Banca Sella Group", "Finanza / Banche", "64.19"],
    ["Illimity Bank", "Finanza / Banche", "64.19"],
    ["Credito Fondiario", "Finanza / Banche", "64.19"],

    # --- EDILIZIA, COSTRUZIONI E MATERIALI (ATECO 41-43, 23) ---
    ["Webuild S.p.A.", "Costruzioni / Grandi Opere", "42.11"],
    ["Maire Tecnimont S.p.A.", "Costruzioni / Impianti", "42.99"],
    ["Buzzi Unicem S.p.A.", "Materiali / Cemento", "23.51"],
    ["Cementir Holding", "Materiali / Cemento", "23.51"],
    ["Mapei S.p.A.", "Materiali / Chimica per Edilizia", "20.30"],
    ["Italgraniti Group", "Materiali / Ceramica", "23.31"],
    ["Florim Ceramiche", "Materiali / Ceramica", "23.31"],
    ["Iris Ceramica Group", "Materiali / Ceramica", "23.31"],
    ["Gruppo Concorde", "Materiali / Ceramica", "23.31"],
    ["Kerakoll S.p.A.", "Materiali / Chimica per Edilizia", "20.30"],
    ["Panariagroup", "Materiali / Ceramica", "23.31"],
    ["Laminam S.p.A.", "Materiali / Ceramica", "23.31"],
    ["Vianini Lavori", "Costruzioni / Ingegneria", "42.11"],
    ["Astaldi (now Webuild)", "Costruzioni", "42.11"],
    ["Rizzani de Eccher", "Costruzioni", "41.20"],
    ["Pizzarotti & C.", "Costruzioni", "41.20"],
    ["CMB Cooperativa Muratori", "Costruzioni", "41.20"],
    ["Ghella S.p.A.", "Costruzioni", "42.11"],
    ["Trevi Finanziaria Industriale", "Costruzioni", "42.99"],
    ["Italferr S.p.A.", "Costruzioni / Ingegneria", "71.12"],

    # --- TRASPORTI E LOGISTICA (ATECO 49-52) ---
    ["Ferrovie dello Stato Italiane", "Trasporti / Ferroviario", "49.20"],
    ["Italo - Nuovo Trasporto Viaggiatori", "Trasporti / Ferroviario", "49.20"],
    ["ATM Milano", "Trasporti / Pubblico", "49.31"],
    ["ATAC Roma", "Trasporti / Pubblico", "49.31"],
    ["Autostrade per l'Italia", "Trasporti / Infrastrutture", "52.21"],
    ["Mundys (ex Atlantia)", "Trasporti / Infrastrutture", "52.21"],
    ["Gruber Logistics", "Logistica / Autotrasporto", "49.41"],
    ["Gruppo Autosped G", "Logistica / Trasporto Merci", "49.41"],
    ["Arriva Italia", "Trasporti / Pubblico", "49.31"],
    ["Mercitalia Logistics", "Logistica / Ferroviario", "52.29"],
    ["Trans Italia", "Logistica / Intermodale", "49.41"],
    ["Ambrogio Intermodal", "Logistica / Intermodale", "52.29"],
    ["Interporto Bologna", "Logistica / Hub", "52.10"],
    ["Intermodaltrasporti", "Logistica / Trasporto Merci", "49.41"],
    ["Fercam S.p.A.", "Logistica / Trasporto Merci", "49.41"],
    ["BRT S.p.A.", "Logistica / Corriere", "53.20"],
    ["SDA Express Courier", "Logistica / Corriere", "53.20"],
    ["Savino Del Bene", "Logistica / Spedizioni", "52.29"],
    ["BCube", "Logistica / Spedizioni", "52.29"],
    ["Arcese Trasporti", "Logistica / Autotrasporto", "49.41"],

    # --- SERVIZI IT, CONSULENZA E TELECOMUNICAZIONI (ATECO 61-62, 70-74) ---
    ["Telecom Italia (TIM)", "Telecomunicazioni", "61.10"],
    ["Vodafone Italia", "Telecomunicazioni", "61.20"],
    ["Fastweb S.p.A.", "Telecomunicazioni", "61.20"],
    ["Wind Tre S.p.A.", "Telecomunicazioni", "61.20"],
    ["Reply S.p.A.", "Servizi IT / Software", "62.01"],
    ["Engineering Ingegneria Informatica", "Servizi IT / Consulenza", "62.02"],
    ["Almaviva S.p.A.", "Servizi IT / Consulenza", "62.02"],
    ["Zucchetti Group", "Servizi IT / Software", "62.01"],
    ["TeamSystem S.p.A.", "Servizi IT / Software", "62.01"],
    ["Dedagroup", "Servizi IT / Software", "62.01"],
    ["WeAreProject", "Servizi IT / System Integrator", "62.09"],
    ["Quanture", "Servizi IT / Consulenza", "62.02"],
    ["Var Group", "Servizi IT / System Integrator", "62.02"],
    ["Lutech S.p.A.", "Servizi IT / Consulenza", "62.02"],
    ["Crif S.p.A.", "Servizi IT / Dati", "62.09"],
    ["Cerved Group", "Servizi IT / Dati", "63.99"],
    ["Jakala Società Benefit", "Servizi / Marketing", "73.11"],
    ["SG Company", "Servizi / Eventi", "73.11"],
    ["Tinexta S.p.A.", "Servizi IT / Trust Services", "62.09"],
    ["Sesa S.p.A.", "Servizi IT / System Integrator", "62.02"],

    # --- CHIMICA, FARMA E COSMETICA (ATECO 20-21) ---
    ["Recordati S.p.A.", "Farmaceutica", "21.20"],
    ["Diasorin S.p.A.", "Farmaceutica / Diagnostica", "21.20"],
    ["Amplifon S.p.A.", "Farmaceutica / Dispositivi", "26.60"],
    ["Chiesi Farmaceutici", "Farmaceutica", "21.20"],
    ["Menarini Group", "Farmaceutica", "21.20"],
    ["Zambon S.p.A.", "Farmaceutica", "21.20"],
    ["Bracco S.p.A.", "Farmaceutica", "21.20"],
    ["Angelini Pharma", "Farmaceutica", "21.20"],
    ["Dompé Farmaceutici", "Farmaceutica", "21.20"],
    ["Fidia Farmaceutici", "Farmaceutica", "21.20"],
    ["Alfasigma S.p.A.", "Farmaceutica", "21.20"],
    ["Versalis (Eni)", "Chimica / Plastica", "20.16"],
    ["Mossi & Ghisolfi", "Chimica / Plastica", "20.16"],
    ["Novamont S.p.A.", "Chimica / Bioplastiche", "20.16"],
    ["Green Oleo S.p.A.", "Chimica / Oleochimica", "20.14"],
    ["WIZ Chemicals", "Chimica", "20.59"],
    ["Davines S.p.A.", "Cosmetica", "20.42"],
    ["Intercos Group", "Cosmetica", "20.42"],
    ["EuroItalia", "Cosmetica", "20.42"],
    ["Kiko Milano", "Cosmetica", "20.42"]
]

file_path = r"C:\Users\g.orsolini\Desktop\Giorgio\Privata\Personale\Nuova-cartella\Progetti\Sostenibilità\Aziende_Bilancio_Sostenibilita_2023_2024.csv"

with open(file_path, mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file, delimiter=';')
    writer.writerow(["Nome Azienda", "Macro-Settore", "Codice ATECO Primario"])
    writer.writerows(aziende)

print(f"File CSV generato con successo: {file_path}")
print(f"Totale aziende censite: {len(aziende)}")
